-- Product image uploads (Cloudflare R2) feature.
-- Run this in the Supabase SQL editor (or `supabase db execute` / psql)
-- against the project's Postgres database. This repo has no local schema/
-- migrations tracking, so this file is the manual record of the change.
--
-- product_id is BIGINT to match products.id (verified against the live
-- schema: bigint, identity BY DEFAULT).

CREATE TABLE IF NOT EXISTS product_images (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  storage_key  TEXT NOT NULL UNIQUE,   -- R2 object key, e.g. products/123/<uuid>.jpg
  url          TEXT NOT NULL,          -- public URL the app serves (R2_PUBLIC_URL + storage_key)
  is_default   BOOLEAN NOT NULL DEFAULT false,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Speeds up "get all images for product X", the app's most common query.
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);

-- Enforces "at most one default image per product" at the database level,
-- not just in application code. A partial unique index only applies to rows
-- where is_default = true, so any number of non-default rows is still fine.
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_images_one_default
  ON product_images(product_id)
  WHERE is_default = true;

-- Every other public-facing table in this project should have RLS enabled.
-- The backend connects with the service_role key (see
-- src/config/supabaseClient.js), which bypasses RLS entirely, so no
-- policies are defined here — add some only if this table is ever queried
-- directly via PostgREST/anon or authenticated Supabase keys, which this
-- backend does not do today.
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
